// FontAwesome configuration
import { library, config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'

// Prevent FA from adding CSS automatically (we import it manually)
config.autoAddCss = false

// Import icons we need
import {
    faSearch,
    faTimes,
    faArrowRight,
    faArrowLeft,
    faImage,
    faSpinner,
    faCheck,
    faDownload,
    faGem,
    faStar,
    faFire,
    faPalette,
    faWandMagicSparkles,
    faCamera,
    faBolt,
    faCircle,
    faChevronRight,
    faChevronLeft,
    faPlus,
    faMinus,
    faUser,
    faBell,
    faCog,
    faHome,
    faHeart,
    faShare,
    faEllipsisV,
    faInfoCircle,
    faExclamationTriangle,
    faCheckCircle,
    faTimesCircle,
    faCopy,
    faQrcode,
    faWallet,
    faCoins,
    faCreditCard,
    faUpload,
    faCloudUploadAlt,
    faMagic,
    faRocket,
    faGift,
    faTag,
    faCrown,
} from '@fortawesome/free-solid-svg-icons'

import {
    faHeart as faHeartRegular,
    faStar as faStarRegular,
    faBell as faBellRegular,
    faImage as faImageRegular,
    faCopy as faCopyRegular,
} from '@fortawesome/free-regular-svg-icons'

import {
    faFacebook,
    faTwitter,
    faInstagram,
    faTiktok,
    faGithub,
} from '@fortawesome/free-brands-svg-icons'

// Add icons to library (global access)
library.add(
    // Solid icons
    faSearch,
    faTimes,
    faArrowRight,
    faArrowLeft,
    faImage,
    faSpinner,
    faCheck,
    faDownload,
    faGem,
    faStar,
    faFire,
    faPalette,
    faWandMagicSparkles,
    faCamera,
    faBolt,
    faCircle,
    faChevronRight,
    faChevronLeft,
    faPlus,
    faMinus,
    faUser,
    faBell,
    faCog,
    faHome,
    faHeart,
    faShare,
    faEllipsisV,
    faInfoCircle,
    faExclamationTriangle,
    faCheckCircle,
    faTimesCircle,
    faCopy,
    faQrcode,
    faWallet,
    faCoins,
    faCreditCard,
    faUpload,
    faCloudUploadAlt,
    faMagic,
    faRocket,
    faGift,
    faTag,
    faCrown,
    // Regular icons
    faHeartRegular,
    faStarRegular,
    faBellRegular,
    faImageRegular,
    faCopyRegular,
    // Brand icons
    faFacebook,
    faTwitter,
    faInstagram,
    faTiktok,
    faGithub
)

export {
    // Re-export commonly used icons
    faSearch,
    faTimes,
    faArrowRight,
    faArrowLeft,
    faImage,
    faSpinner,
    faCheck,
    faDownload,
    faGem,
    faStar,
    faFire,
    faPalette,
    faWandMagicSparkles,
    faCamera,
    faBolt,
    faCircle,
    faChevronRight,
    faChevronLeft,
    faPlus,
    faMinus,
    faUser,
    faBell,
    faCog,
    faHome,
    faHeart,
    faShare,
    faEllipsisV,
    faInfoCircle,
    faExclamationTriangle,
    faCheckCircle,
    faTimesCircle,
    faCopy,
    faQrcode,
    faWallet,
    faCoins,
    faCreditCard,
    faUpload,
    faCloudUploadAlt,
    faMagic,
    faRocket,
    faGift,
    faTag,
    faCrown,
    faHeartRegular,
    faStarRegular,
    faBellRegular,
    faImageRegular,
    faCopyRegular,
    faFacebook,
    faTwitter,
    faInstagram,
    faTiktok,
    faGithub,
}
